name: Run Black check and Test
on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  build:
    name: Install and Test

    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.9]

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install dependencies and Configure
      run: |
        python -m pip install --upgrade pip
        pip install poetry
        poetry install --with dev
    - name: Check with Black
      run: |
        poetry run black --check .
    - name: Run Python tests
      run: |
        poetry run pytest
